---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-creds
  namespace: build
secrets:
- name: registry-creds
imagePullSecrets:
- name: registry-creds

---

apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/go
